### ISSUE TITLE
Failed to add video to download queue: Response 400 from YouTube

### ISSUE THREAD

**Issue by N72826** [bbilly1/tubearchivist#176]
```
https://youtu.be/_JwGJhYQUOQ

processing: https://youtu.be/_JwGJhYQUOQ

ParseResult(scheme='https', netloc='youtu.be', path='/_JwGJhYQUOQ', params='', query='', fragment='')

[{'url': '_JwGJhYQUOQ', 'type': 'video'}]

[2022-02-14 22:49:46,874: INFO/MainProcess] Task home.tasks.extrac_dl[b3bb7caf-4403-4e07-8342-efa788dd1afc] received

[2022-02-14 22:49:46,912: WARNING/ForkPoolWorker-4] <Response [400]>

[2022-02-14 22:49:47,023: ERROR/ForkPoolWorker-4] Task home.tasks.extrac_dl[b3bb7caf-4403-4e07-8342-efa788dd1afc] raised unexpected: ValueError('failed to add video to download queue')

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__

    return self.run(*args, **kwargs)

  File "/app/home/tasks.py", line 133, in extrac_dl

    all_videos_added = pending_handler.add_to_pending(missing_videos)

  File "/app/home/src/download/queue.py", line 87, in add_to_pending

    raise ValueError("failed to add video to download queue")

ValueError: failed to add video to download queue
```

**Comment by bbilly1** [comment]
Hmm, I can't reproduce that. Both adding to download queue and downloading and indexing works fine for me.

- Is it possible that you have network issues?
- yt-dlp added some fixes recently. Did you update to latest v0.1.1?

**Comment by N72826** [comment]
>     * yt-dlp added some fixes recently. Did you update to latest v0.1.1?

I thought yt-dlp updated along with the container?

**Comment by bbilly1** [comment]
Yes, when you update Tube Archivist, you'll get the latest version from when the image was released.

**Comment by N72826** [comment]
ok, cool, watchtower(automated image updating container) just updated the tubearchivist yesterday. I'll see if it's a network issue then, I'll restart the system.

**Comment by N72826** [comment]
Ok, so it's still happening. My scheduled downloads successfully complete though, it's only when I manually add something.

**Comment by N72826** [comment]
ok wtf. The error only occurs with that one channel. I tried another video and it works, just as my scheduled downloads work since theyh are from other channels.

**Comment by bbilly1** [comment]
Did that solve itself? Or are you still seeing that error?

I think I saw a similar issue on my side, that was purely YouTube related and a VPN reload solved that problem for me...
