### ISSUE TITLE
ElasticSearch Redis unable to connect

### ISSUE THREAD

**Issue by muppie** [bbilly1/tubearchivist#43]
Hi!

I’m running this image on my unraid box with separate containers for Redis and ElasticSearch since I have other uses for these containers as well. I’m unable to get past Internal Server Error. Attaching log files further down. Does anything look strange? Reach out if additional information on Unraid is needed/wanted.

`os: Linux-5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021
nodename: 864dd501bb25
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /app
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

your processes number limit is 191529
your memory page size is 4096 bytes
detected max file descriptor number: 40960
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

Python version: 3.9.7 (default, Sep 3 2021, 02:02:37) [GCC 10.2.1 20210110]

*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x556780637870
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
File "/app/./config/wsgi.py", line 16, in <module>
application = get_wsgi_application()
File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
app_config = AppConfig.create(entry)
File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 212, in create
mod = import_module(mod_path)
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/app/./home/__init__.py", line 7, in <module>
from home.src.index_management import index_check
File "/app/./home/src/index_management.py", line 160, in <module>
class ElasticIndex:
File "/app/./home/src/index_management.py", line 165, in ElasticIndex
CONFIG = AppConfig().config
File "/app/./home/src/config.py", line 18, in __init__
self.config = self.get_config()
File "/app/./home/src/config.py", line 22, in get_config
config = self.get_config_redis()
File "/app/./home/src/config.py", line 54, in get_config_redis
config = get_message("config")
File "/app/./home/src/helper.py", line 96, in get_message
reply = redis_connection.execute_command("JSON.GET", key)
File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
return self.parse_response(conn, command_name, **options)
File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
response = connection.read_response()
File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
raise response
redis.exceptions.ResponseError: unknown command `JSON.GET`, with args beginning with: `config`,
unable to load app 0 (mountpoint='') (callable not found or import error)

*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app':

Unable to load celery application.
While trying to load the module home.tasks the following error occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 53, in convert
return find_app(value)
File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
sym = symbol_by_name(app, imp=imp)
File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
module = imp(module_name, package=package, **kwargs)
File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
return imp(module, package=package)
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/app/home/__init__.py", line 7, in <module>
from home.src.index_management import index_check
File "/app/home/src/index_management.py", line 160, in <module>
class ElasticIndex:
File "/app/home/src/index_management.py", line 165, in ElasticIndex
CONFIG = AppConfig().config
File "/app/home/src/config.py", line 18, in __init__
self.config = self.get_config()
File "/app/home/src/config.py", line 22, in get_config
config = self.get_config_redis()
File "/app/home/src/config.py", line 54, in get_config_redis
config = get_message("config")
File "/app/home/src/helper.py", line 96, in get_message
reply = redis_connection.execute_command("JSON.GET", key)
File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
return self.parse_response(conn, command_name, **options)
File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
response = connection.read_response()
File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
raise response
redis.exceptions.ResponseError: unknown command `JSON.GET`, with args beginning with: `config`,

--- no python application found, check your startup logs for errors ---
[pid: 22|app: -1|req: -1/1] 10.0.8.2 () {40 vars in 650 bytes} [Sat Oct 2 20:20:37 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22|app: -1|req: -1/2] 10.0.8.2 () {40 vars in 620 bytes} [Sat Oct 2 20:20:38 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0) `

**Comment by lamusmaser** [comment]
Based on the error messages, it looks like your redis is the core version. This application utilizes redis JSON (or rejson) from RedisLabs.
You would have to either rebuild your redis with the rejson package or build a standalone container for the rejson container, which this application would utilize.

**Comment by bbilly1** [comment]
Maybe you haven't seen it, there is a unraid [forum post](https://forums.unraid.net/topic/114073-support-crocs-tube-archivist/) that goes into more details and has some screenshots on how to create the needed containers.

**Comment by bbilly1** [comment]
closing due to inactivity.
