### ISSUE TITLE
KeyError: 'default_view'

### ISSUE THREAD

**Issue by seriousm4x** [bbilly1/tubearchivist#45]
Just updated from an old version (actually don't know which) to 0.0.5. I'm getting a key error on line 112 in views.py.

```
tubearchivist      | 2021-10-03T16:35:27.550508323Z Internal Server Error: /
tubearchivist      | 2021-10-03T16:35:27.550553105Z Traceback (most recent call last):
tubearchivist      | 2021-10-03T16:35:27.550557585Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
tubearchivist      | 2021-10-03T16:35:27.550560572Z     response = get_response(request)
tubearchivist      | 2021-10-03T16:35:27.550563325Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
tubearchivist      | 2021-10-03T16:35:27.550565996Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tubearchivist      | 2021-10-03T16:35:27.550568542Z   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
tubearchivist      | 2021-10-03T16:35:27.550571161Z     return self.dispatch(request, *args, **kwargs)
tubearchivist      | 2021-10-03T16:35:27.550573643Z   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
tubearchivist      | 2021-10-03T16:35:27.550576174Z     return handler(request, *args, **kwargs)
tubearchivist      | 2021-10-03T16:35:27.550578713Z   File "/app/./home/views.py", line 42, in get
tubearchivist      | 2021-10-03T16:35:27.550581349Z     colors, view_style, sort_order, hide_watched = self.read_config()
tubearchivist      | 2021-10-03T16:35:27.550583820Z   File "/app/./home/views.py", line 112, in read_config
tubearchivist      | 2021-10-03T16:35:27.550586455Z     view_style = config_handler["default_view"]["home"]
tubearchivist      | 2021-10-03T16:35:27.550589565Z KeyError: 'default_view'
tubearchivist      | 2021-10-03T16:35:27.550672734Z [pid: 31|app: 0|req: 34/34] 172.21.0.1 () {58 vars in 935 bytes} [Sun Oct  3 16:35:27 2021] GET / => generated 69214 bytes in 29 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
```

**Comment by bbilly1** [comment]
OK, try to pull the image again and rebuild. I messed up the refactoring. It should load the new config defaults for v0.0.5 correctly on startup.

**Comment by seriousm4x** [comment]
Weird. I tried that before. I stopped all containers, deleted the images and pulled them again.

Second time now I did the same but also changed permissions for all files in the mount points.

Seems to be working now again. I'd close this unless you want to dig deeper.
